import { TraceabilityLot, TraceabilityStep, ProduceQualityGrade } from '@/types/intelligence';

export function getTraceabilityLot(lotId: string = 'LOT-2026-7842'): TraceabilityLot {
  const steps: TraceabilityStep[] = [
    {
      stepNumber: 1,
      phase: 'Farm Origin & Plot Geofencing',
      timestamp: '2026-09-02 06:30 IST',
      location: 'Plot 4B, Zaheerabad, Sangareddy, Telangana',
      actor: 'Ramesh Patel (Farmer ID: FRM-7821)',
      status: 'COMPLETED',
      verifiedHash: '0x8f2a1b94c03e8712f5a01bc',
      details: { variety: 'Hybrid Desi Tomato', acreage: '2.5 Acres', soilType: 'Red Loam', organicCarbon: '0.78%' },
    },
    {
      stepNumber: 2,
      phase: 'Weather Event & Shock Impact Audit',
      timestamp: '2026-09-06 14:15 IST',
      location: 'IMD Automated Weather Station, Sangareddy',
      actor: 'AgriFlow Weather Oracle',
      status: 'COMPLETED',
      verifiedHash: '0x3c990df124a56e9871ab872',
      details: { event: 'Unseasonal High Rain (78mm)', harvestLossAssessed: '40% (400 kg)', survivingSupply: '600 kg' },
    },
    {
      stepNumber: 3,
      phase: 'Field Harvesting & Sorting',
      timestamp: '2026-09-08 07:00 IST',
      location: 'Zaheerabad Farm Packhouse',
      actor: 'Harvest Crew Lead: S. Ramulu',
      status: 'COMPLETED',
      verifiedHash: '0x17db44fa8001e956bc22941',
      details: { grossHarvestKg: 1000, sortedMarketableKg: 600, sortingEfficiency: '98.2%' },
    },
    {
      stepNumber: 4,
      phase: 'AI Computer-Vision Quality Grading',
      timestamp: '2026-09-08 08:30 IST',
      location: 'AgriFlow Mobile Inspection Terminal',
      actor: 'AgriFlow Vision Engine v2.4',
      status: 'COMPLETED',
      verifiedHash: '0x7e883a904fc192837bcde01',
      details: { gradeAssigned: 'Grade B (Premium Desi)', blemishRate: '3.4%', avgDiameter: '64mm', confidence: '94%' },
    },
    {
      stepNumber: 5,
      phase: 'Dynamic Market Pricing & Buyer Match',
      timestamp: '2026-09-08 09:15 IST',
      location: 'AgriFlow Pricing Gateway Engine',
      actor: 'AgriFlow AI Pricing Coordinator',
      status: 'COMPLETED',
      verifiedHash: '0x5b32a9001c385f817ea8910',
      details: {
        minimumSustainablePrice: '₹35.83/kg',
        calculatedShockPrice: '₹52.92/kg',
        buyerMatched: 'Reliance Fresh Distribution Center',
        contractPrice: '₹54.00/kg',
      },
    },
    {
      stepNumber: 6,
      phase: 'Reefer Loading & IoT Sensor Seal',
      timestamp: '2026-09-08 11:00 IST',
      location: 'Zaheerabad Reefer Dock',
      actor: 'Driver: Suresh Kumar (Tata 407 Reefer TS-08-UB-4491)',
      status: 'COMPLETED',
      verifiedHash: '0x992cf00192847aefbc00821',
      details: { setpointTemp: '12.0°C', initialTemp: '12.4°C', initialRH: '90%', eLockSealId: 'SEAL-HYD-9912' },
    },
    {
      stepNumber: 7,
      phase: 'Cold-Chain IoT Telemetry Audit',
      timestamp: '2026-09-08 12:45 IST',
      location: 'En-route NH65 (Outer Ring Road KM 44)',
      actor: 'IoT Telemetry Gateway',
      status: 'COMPLETED',
      verifiedHash: '0x41ab982736fc001928371ef',
      details: { avgTemp: '12.6°C', maxTemp: '13.1°C', humidity: '89%', compressorUptime: '99.4%', status: 'GREEN_PASS' },
    },
    {
      stepNumber: 8,
      phase: 'Destination Hub QC & Digital Gate Pass',
      timestamp: '2026-09-08 14:10 IST',
      location: 'Shamshabad Distribution Park Gate 2',
      actor: 'QC Inspector: Vivek Reddy',
      status: 'COMPLETED',
      verifiedHash: '0x6291ba88273619283fa0012',
      details: { weightReceivedKg: 598.4, weightToleranceVarianceKg: '-1.6 kg (-0.26%)', qcGradeVerified: 'Grade B (Approved)' },
    },
    {
      stepNumber: 9,
      phase: 'Buyer Acceptance & Escrow Release',
      timestamp: '2026-09-08 14:35 IST',
      location: 'Reliance Fresh Inward Dock',
      actor: 'Category Manager: Priya Sharma',
      status: 'COMPLETED',
      verifiedHash: '0x93bb0019283746aefc88219',
      details: { invoiceAmount: '₹32,313.60', freightDeduction: '₹0 (Farm Pickup)', netApprovedValue: '₹32,313.60' },
    },
    {
      stepNumber: 10,
      phase: 'Instant Bank Payout & Traceability NFT Receipt',
      timestamp: '2026-09-08 14:40 IST',
      location: 'NPCI UPI / Canara Bank Farmer Account',
      actor: 'AgriFlow Smart Contract Settlement',
      status: 'COMPLETED',
      verifiedHash: '0x00192837465afcb81928371',
      details: { utrNumber: 'UTR-202609087719284', settledAmount: '₹32,313.60', payoutSpeed: '5 mins from dock QC' },
    },
  ];

  return {
    lotId,
    commodity: 'Tomato (Hybrid Desi)',
    variety: 'US-440 Desi Selection',
    farmerName: 'Ramesh Patel',
    farmLocation: 'Zaheerabad, Sangareddy, Telangana',
    harvestDate: '08 Sep 2026',
    initialQuantityKg: 1000,
    marketableQuantityKg: 600,
    assignedGrade: 'Grade B',
    soilHealthScore: 84,
    weatherShockHistory: 'Excessive Rainfall (40% damage, dynamic shortage compensated)',
    coldChainTelemetryVerified: true,
    qrCodeDataUrl: `https://api.qrserver.com/v1/create-qr-code/?size=180x180&data=https://agriflow.ai/traceability/${lotId}`,
    currentStatus: 'Settled & Delivered',
    buyerName: 'Reliance Fresh Distribution Center',
    finalPayoutPerKg: 54.00,
    steps,
  };
}
