import { ConsumerProduct, BulkDemandPost } from '@/types/consumer';

export const mockConsumerProducts: ConsumerProduct[] = [
  {
    id: 'prod-cons-01',
    name: 'Tomato (Hybrid Desi)',
    hindiName: 'टमाटर (देसी संकर)',
    category: 'Vegetables',
    farmerName: 'Ramesh Reddy & Shadnagar FPO',
    farmLocation: 'Shadnagar Cluster, Rangareddy, Telangana',
    fpoCluster: 'Shadnagar Organic Growers FPO',
    grade: 'A',
    availableKg: 2400,
    minOrderKg: 50,
    consumerPricePerKg: 42.00,
    farmerRealizationPerKg: 36.50,
    logisticsFeePerKg: 3.50,
    platformFeePerKg: 2.00,
    harvestDate: '2026-09-06',
    harvestHoursAgo: 14,
    coldChainTempCelsius: 6.2,
    freshnessScore: 96,
    image: 'https://images.unsplash.com/photo-1592924357228-91a4daadcfea?auto=format&fit=crop&w=600&q=80',
    description: 'Fresh farm-gate harvested hybrid tomatoes. Zero artificial ripening. Packed in aerated food-grade crates with cold-chain provenance.',
    provenanceBatchId: 'BATCH-TS-SHAD-9021',
  },
  {
    id: 'prod-cons-02',
    name: 'Green Chilli (G4 Spicy)',
    hindiName: 'हरी मिर्च (जी4)',
    category: 'Spices',
    farmerName: 'Venkatesh Rao & Guntur Cluster',
    farmLocation: 'Guntur Rural, Andhra Pradesh',
    fpoCluster: 'Andhra Spice Growers Collective',
    grade: 'A-',
    availableKg: 1200,
    minOrderKg: 25,
    consumerPricePerKg: 58.00,
    farmerRealizationPerKg: 50.00,
    logisticsFeePerKg: 5.00,
    platformFeePerKg: 3.00,
    harvestDate: '2026-09-05',
    harvestHoursAgo: 22,
    coldChainTempCelsius: 8.5,
    freshnessScore: 92,
    image: 'https://images.unsplash.com/photo-1588252303782-cb80119abd6d?auto=format&fit=crop&w=600&q=80',
    description: 'Export-grade spicy G4 green chillies. Machine sorted for length and stem freshness. Direct dispatch via insulated Bolero freight.',
    provenanceBatchId: 'BATCH-AP-GNT-8812',
  },
  {
    id: 'prod-cons-03',
    name: 'Red Onion (Nasik Hybrid)',
    hindiName: 'लाल प्याज (नासिक)',
    category: 'Vegetables',
    farmerName: 'Balaji Agro Farmers Society',
    farmLocation: 'Medak, Telangana',
    fpoCluster: 'Medak Vegetable Growers Collective',
    grade: 'B+',
    availableKg: 4000,
    minOrderKg: 100,
    consumerPricePerKg: 28.00,
    farmerRealizationPerKg: 23.50,
    logisticsFeePerKg: 3.00,
    platformFeePerKg: 1.50,
    harvestDate: '2026-09-04',
    harvestHoursAgo: 48,
    coldChainTempCelsius: 14.0,
    freshnessScore: 88,
    image: 'https://images.unsplash.com/photo-1618512496248-a07fe83aa8cb?auto=format&fit=crop&w=600&q=80',
    description: 'Cured red onions with tight skins, optimal for institutional bulk kitchens, catering, and retail distribution.',
    provenanceBatchId: 'BATCH-TS-MDK-7721',
  },
  {
    id: 'prod-cons-04',
    name: 'Potato (Jyoti Fresh Table)',
    hindiName: 'आलू (ज्योति)',
    category: 'Tubers',
    farmerName: 'Zaheerabad Farm Center',
    farmLocation: 'Zaheerabad, Sangareddy, Telangana',
    fpoCluster: 'Deccan Tuber Collective',
    grade: 'A',
    availableKg: 3500,
    minOrderKg: 100,
    consumerPricePerKg: 22.00,
    farmerRealizationPerKg: 18.00,
    logisticsFeePerKg: 2.50,
    platformFeePerKg: 1.50,
    harvestDate: '2026-09-05',
    harvestHoursAgo: 30,
    coldChainTempCelsius: 12.0,
    freshnessScore: 94,
    image: 'https://images.unsplash.com/photo-1518977676601-b53f82aba655?auto=format&fit=crop&w=600&q=80',
    description: 'Clean washed table potatoes, uniform 55mm+ sizing, low sugar content ideal for institutional cooking and fry usage.',
    provenanceBatchId: 'BATCH-TS-ZHB-6632',
  }
];

export const mockBulkDemands: BulkDemandPost[] = [
  {
    id: 'DEM-HYD-5000',
    buyerName: 'Bowenpally Institutional Wholesale & Retail Consortium',
    buyerType: 'Bulk Retail & Commercial Buyer',
    commodity: 'Tomato (Hybrid Desi)',
    requiredQuantityKg: 5000,
    maxTargetPricePerKg: 42.00,
    deliveryLocation: 'Bowenpally Agri Terminal Gate 3, Hyderabad',
    targetDate: '2026-09-07',
    status: 'Consolidated',
    allocatedFarmers: [
      { farmerName: 'Ramesh Reddy (Shadnagar FPO)', location: 'Shadnagar, Telangana', allocatedKg: 2400, grade: 'A' },
      { farmerName: 'Suresh Kumar (Chevella Unit)', location: 'Chevella, Telangana', allocatedKg: 1600, grade: 'A' },
      { farmerName: 'Laxmi Farmers Self-Help Group', location: 'Farooqnagar, Telangana', allocatedKg: 1000, grade: 'A-' },
    ],
    createdAt: '2026-09-05T08:00:00Z',
  },
  {
    id: 'DEM-VJA-3000',
    buyerName: 'Andhra Food Processors Ltd',
    buyerType: 'Food Processor & Pickles',
    commodity: 'Green Chilli (G4)',
    requiredQuantityKg: 3000,
    maxTargetPricePerKg: 58.00,
    deliveryLocation: 'Autonagar Industrial Hub, Vijayawada',
    targetDate: '2026-09-08',
    status: 'Open',
    allocatedFarmers: [
      { farmerName: 'Guntur Spice Cluster A', location: 'Guntur, AP', allocatedKg: 1200, grade: 'A-' },
      { farmerName: 'Krishna Valley Growers', location: 'Tenali, AP', allocatedKg: 600, grade: 'A' },
    ],
    createdAt: '2026-09-06T10:00:00Z',
  }
];
