import { Order, RoadLogisticsTracking } from "@/types/farmer";

export const mockOrders: Order[] = [
  {
    id: "ORD-78921",
    buyerName: "FreshDirect Hypermarkets Pvt Ltd",
    buyerType: "Institutional Retail Buyer",
    produceName: "Tomato (Hybrid Desi)",
    quantityKg: 2400,
    grade: "A",
    pricePerKg: 42.00,
    totalOrderValue: 100800,
    orderDate: "2026-09-05",
    pickupDate: "2026-09-06 09:30 AM",
    deliveryDate: "2026-09-06 05:45 PM",
    status: "In Transit",
    logisticsId: "TRK-RD-9021",
    destinationCity: "Hyderabad, Telangana",
  },
  {
    id: "ORD-78410",
    buyerName: "Telangana Agri Processing Co.",
    buyerType: "Food Processor",
    produceName: "Green Chilli (G4)",
    quantityKg: 1200,
    grade: "A-",
    pricePerKg: 58.00,
    totalOrderValue: 69600,
    orderDate: "2026-09-04",
    pickupDate: "2026-09-05",
    deliveryDate: "2026-09-05",
    status: "Delivered",
    logisticsId: "TRK-RD-8812",
    destinationCity: "Warangal, Telangana",
  },
  {
    id: "ORD-79102",
    buyerName: "Southern Retail Hubs",
    buyerType: "Consortium Buyer",
    produceName: "Onion (Nashik Red)",
    quantityKg: 5000,
    grade: "B",
    pricePerKg: 28.00,
    totalOrderValue: 140000,
    orderDate: "2026-09-06",
    pickupDate: "2026-09-07 10:00 AM",
    status: "Confirmed",
    logisticsId: "TRK-RD-9140",
    destinationCity: "Hyderabad, Telangana",
  }
];

export const mockTrackingDetails: Record<string, RoadLogisticsTracking> = {
  "TRK-RD-9021": {
    id: "TRK-RD-9021",
    orderId: "ORD-78921",
    vehicleType: "Tata 407 Reefer",
    vehicleNumber: "TS 08 UB 4192",
    driverName: "Mohammed Ismail",
    driverPhone: "+91 98480 22341",
    pickupLocation: "Shadnagar FPO Hub, Telangana",
    destinationLocation: "Bowenpally Agri Hub, Hyderabad",
    currentLocationName: "Shamshabad Outer Ring Road Tollway",
    currentCoordinates: [17.2403, 78.4294],
    pickupCoordinates: [17.0684, 78.2078],
    destinationCoordinates: [17.4729, 78.4842],
    estimatedArrival: "Today, 05:45 PM",
    status: "In Transit",
    progressPercent: 68,
    distanceRemainingKm: 28,
    totalDistanceKm: 74,
    isSimulatedGPS: true,
    spoilageTelemetry: {
      temperatureCelsius: 6.2,
      targetTempCelsius: 6.0,
      humidityPercent: 88,
      safeWindowHours: 4,
      safeWindowMinutes: 32,
      riskLevel: "Low",
      isSimulated: true,
    },
    returnLoad: {
      id: "RET-HYD-WGL-01",
      origin: "Hyderabad Agri Terminal",
      destination: "Warangal Produce Hub",
      commodity: "Organic Fertilizer Sacks & Seedlings",
      additionalEarnings: 2800,
      emptyDistanceAvoidedKm: 142,
      status: "Available",
      isDemoData: true,
    },
    timeline: [
      { title: "Produce Loaded & Graded", location: "Shadnagar FPO Hub", timestamp: "09:30 AM", completed: true },
      { title: "Driver Assigned & Inspected", location: "Tata 407 Reefer (TS 08 UB 4192)", timestamp: "10:00 AM", completed: true },
      { title: "Trip Started (Road Route)", location: "Departed Shadnagar", timestamp: "10:30 AM", completed: true },
      { title: "In Transit - ORR Corridor", location: "Shamshabad (Speed: 52 km/h)", timestamp: "03:15 PM", completed: true, current: true },
      { title: "Arrival at Destination", location: "Bowenpally Agri Hub, Hyderabad", timestamp: "05:45 PM (ETA)", completed: false },
      { title: "Unloading & Payment Release", location: "Inspection Gate 3", timestamp: "Pending", completed: false },
    ],
  },
};
