import { MarketPrice, PriceTrendPoint } from "@/types/farmer";

export const mockMarketPrices: MarketPrice[] = [
  {
    id: "mp-001",
    commodity: "Tomato",
    marketName: "Hyderabad (Bowenpally)",
    district: "Hyderabad",
    state: "Telangana",
    currentPrice: 38.00,
    previousPrice: 35.50,
    change: 2.50,
    percentageChange: 7.04,
    bulkBuyerOpportunityPrice: 42.00,
    date: "2026-09-06",
  },
  {
    id: "mp-002",
    commodity: "Tomato",
    marketName: "Gaddiannaram Mandi",
    district: "Rangareddy",
    state: "Telangana",
    currentPrice: 36.50,
    previousPrice: 36.00,
    change: 0.50,
    percentageChange: 1.39,
    bulkBuyerOpportunityPrice: 41.50,
    date: "2026-09-06",
  },
  {
    id: "mp-003",
    commodity: "Tomato",
    marketName: "Kolar Mandi",
    district: "Kolar",
    state: "Karnataka",
    currentPrice: 34.00,
    previousPrice: 36.00,
    change: -2.00,
    percentageChange: -5.55,
    bulkBuyerOpportunityPrice: 39.00,
    date: "2026-09-06",
  },
  {
    id: "mp-004",
    commodity: "Green Chilli",
    marketName: "Warangal Mandi",
    district: "Warangal",
    state: "Telangana",
    currentPrice: 52.00,
    previousPrice: 49.00,
    change: 3.00,
    percentageChange: 6.12,
    bulkBuyerOpportunityPrice: 58.00,
    date: "2026-09-06",
  },
  {
    id: "mp-005",
    commodity: "Onion",
    marketName: "Mahabubnagar Mandi",
    district: "Mahabubnagar",
    state: "Telangana",
    currentPrice: 24.50,
    previousPrice: 24.00,
    change: 0.50,
    percentageChange: 2.08,
    bulkBuyerOpportunityPrice: 28.00,
    date: "2026-09-06",
  },
  {
    id: "mp-006",
    commodity: "Potato",
    marketName: "Nizamabad Mandi",
    district: "Nizamabad",
    state: "Telangana",
    currentPrice: 19.00,
    previousPrice: 19.50,
    change: -0.50,
    percentageChange: -2.56,
    bulkBuyerOpportunityPrice: 22.50,
    date: "2026-09-06",
  }
];

export const mockPriceTrendData: PriceTrendPoint[] = [
  { day: "Day -6", currentMandi: 33.5, forecastedPrice: 33.5, buyerDemandPrice: 37.0 },
  { day: "Day -4", currentMandi: 34.0, forecastedPrice: 34.5, buyerDemandPrice: 38.5 },
  { day: "Day -2", currentMandi: 36.0, forecastedPrice: 36.0, buyerDemandPrice: 40.0 },
  { day: "Today", currentMandi: 38.0, forecastedPrice: 38.0, buyerDemandPrice: 42.0 },
  { day: "Day +2", currentMandi: 39.2, forecastedPrice: 39.8, buyerDemandPrice: 43.5 },
  { day: "Day +4 (Best)", currentMandi: 40.0, forecastedPrice: 41.2, buyerDemandPrice: 45.0 },
  { day: "Day +6", currentMandi: 39.0, forecastedPrice: 39.5, buyerDemandPrice: 43.0 },
];
