import { Produce } from "@/types/farmer";

export const initialProduceList: Produce[] = [
  {
    id: "prod-001",
    crop: "Tomato (Hybrid)",
    quantity: 2400,
    unit: "kg",
    grade: "A",
    harvestDate: "2026-09-04",
    expectedPrice: 42,
    location: "Shadnagar FPO Cluster, Telangana",
    status: "Active",
    notes: "Uniform red ripeness, 0 defects, stored in crate units.",
    createdAt: "2026-09-04T08:30:00Z",
  },
  {
    id: "prod-002",
    crop: "Green Chilli (G4)",
    quantity: 1200,
    unit: "kg",
    grade: "A-",
    harvestDate: "2026-09-05",
    expectedPrice: 58,
    location: "Guntur Rural, Andhra Pradesh",
    status: "Active",
    notes: "Dark green, strong spice profile, clean sorted.",
    createdAt: "2026-09-05T10:15:00Z",
  },
  {
    id: "prod-003",
    crop: "Onion (Nashik Red)",
    quantity: 5000,
    unit: "kg",
    grade: "B",
    harvestDate: "2026-08-28",
    expectedPrice: 28,
    location: "Medak FPO Hub, Telangana",
    status: "Reserved",
    notes: "Medium bulb diameter, dry outer skin.",
    createdAt: "2026-08-28T14:00:00Z",
  },
  {
    id: "prod-004",
    crop: "Potato (Jyoti)",
    quantity: 3500,
    unit: "kg",
    grade: "A",
    harvestDate: "2026-08-20",
    expectedPrice: 22,
    location: "Zaheerabad Farm Center, Telangana",
    status: "Sold",
    notes: "Delivered to Hyderabad Quick Commerce Dark Store.",
    createdAt: "2026-08-20T09:00:00Z",
  }
];
